spring.application.name=webprak

spring.datasource.url=jdbc:postgresql://postgres:5432/personnel
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# We create the schemes using SQL-scripts, not Hibernate.
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=hr
spring.jpa.open-in-view=false

